export enum WALLET_EVENT {
  WALLET_UNLOCKED = "WALLET_UNLOCKED",
  WALLET_LOCKED = "WALLET_LOCKED",
  WALLET_REQUEST = "WALLET_REQUEST",
  WALLET_RESPONSE = "WALLET_RESPONSE",
  CHAIN_CHANGED = "CHAIN_CHANGED",
  ACCOUNTS_CHANGED = "ACCOUNTS_CHANGED",
}
