export enum MESSAGE {
  UNLOCK_WALLET = "UNLOCK_WALLET",
  IS_WALLET_UNLOCKED = "IS_WALLET_UNLOCKED",
  ENABLE_WALLET = "ENABLE_WALLET",
  ETH_REQUEST = "ETH_REQUEST",
  WALLET_REQUEST = "WALLET_REQUEST",
}
